### ISSUE TITLE
OverflowError when using SetImage inside Python thread

### ISSUE THREAD

**Issue by Kleinspider** [hzeller/rpi-rgb-led-matrix#1056]
Thanks for making this great project! Everything has been working great except I cannot seem to get the SetImage function to work from inside a thread in Python. The same code works when it is not inside a thread, but whenever I call SetImage from inside my "renderer" thread I get an OverflowError. 

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/led-matrix-controller/matrix/renderers/main_renderer.py", line 87, in run
    self.current.render(self.canvas)
  File "/home/pi/led-matrix-controller/matrix/renderers/weather_renderer.py", line 55, in render
    self.__render_forecast()
  File "/home/pi/led-matrix-controller/matrix/renderers/weather_renderer.py", line 62, in __render_forecast
    self.matrix.SetImage(im.convert('RGB'), x, 13)
  File "core.pyx", line 22, in rgbmatrix.core.Canvas.SetImage
  File "core.pyx", line 46, in rgbmatrix.core.Canvas.SetPixelsPillow
OverflowError: can't convert negative value to size_t
```
I saw there were a couple other Issues that mentioned this error but I am not sure if there was ever a solution/workaround given for this Issue. Thanks!

**Comment by hzeller** [comment]
Sounds like something happening internally to the Python mapper where some negative value is converted to an unsigned value, which you have to dig into.

**Comment by cagedev** [comment]
I ran into the same issue. A look at [bindings/python/rgbmatrix/core.pyx](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/bindings/python/rgbmatrix/core.pyx) shows `SetImage` has a default `unsafe` mode. Calling it with `unsafe=False` worked for me.

The comments here also refer to unsafe using 'unsafe pointer acces':
#In unsafe mode we directly access the underlying PIL image array
#in cython, which is considered unsafe pointer accecss,
#however it's super fast and seems to work fine
#https://groups.google.com/forum/#!topic/cython-users/Dc1ft5W6KM4

**Comment by cagedev** [comment]
#795

**Comment by marcmerlin** [comment]
With apologies to everyone, this project is doing a one time cleanup of 
all the bugs that have not been addressed and closed in the last 10 years.

If you filed an issue to ask for help, please do not re-open this one or a new
bug, but go here instead: https://rpi-rgb-led-matrix.discourse.group/

Please be mindful that this project does not have any full time maintainers
or anyone paid. You should not expect personal help for your own projects or
answers to programming questions but you can ask for help with panels that
aren't working, setup questions, or anything that may be a bug here:
https://rpi-rgb-led-matrix.discourse.group/
If you need programming help and are willing to pay someone for it, please
state so in your message, and someone may be interested.

If you did report an actual bug that is still not fixed today, please accept
our apologies for this being mass closed, you can absolutely send a followup
and re-open the issue, or open a new up to date one as applicable.
Note that we very much welcome help, so if you can help fix your bug, you will
be a superstar :)

If your bug was linked to a pull request that was not resolved, please update
the pull request and the issue, and we will do our best to review them. We do
thank you for your undertanding that we have very limited free time, so any
extra work you do along with your bug report or PR request will be very much
appreciated and improve the odds that they will be looked at.

If you want to help contribute as a python or C# or any other language bindings,
you are also a superstar, please state so in the issue and we'll do our best to
give you the access and reviews you need.

For anything related to PWM panel support, please make sure you read README and
then refer to https://github.com/hzeller/rpi-rgb-led-matrix/issues/466 . 
Please do not comment if you're haven't read everything and/or if you're just
asking when your panel is going to be supported. Those bugs are if you're 
able to contribute to the effort.

For rPI5: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1603

For anything python, please link your bug to: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1828
For anything C#, please link your bug to: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1828
