### ISSUE TITLE
No module named (image / core)

### ISSUE THREAD

**Issue by Gamereric21** [hzeller/rpi-rgb-led-matrix#1287]
Hi!  Id like to start off by saying im a beginner, and from looking through other issues, im not quite certain exactly what they were doing / supposed to do (in fairness they were in college for computer science)

Ive followed a few tutorials, on of them being a nextbus project from adafruit, one of them being an NBA scoreboard, and one an NHL scoreboard, and no matter what project I do I always get a no module named --- error.

I was trying to run a board test code in rgb-led-matrix (NBA scoreboard), and this is the error message I got

```
@raspberrypi:~/NBA-scoreboard/rpi-rgb-led-matrix/bindings/python/samples $ sudo python3 graphics.py
Traceback (most recent call last):
  File "graphics.py", line 2, in <module>
    from samplebase import SampleBase
  File "/home/pi/NBA-scoreboard/rpi-rgb-led-matrix/bindings/python/samples/samplebase.py", line 7, in <module>
    from rgbmatrix import RGBMatrix, RGBMatrixOptions
  File "/home/pi/NBA-scoreboard/rpi-rgb-led-matrix/bindings/python/rgbmatrix/__init__.py", line 7, in <module>
    from .core import RGBMatrix, FrameCanvas, RGBMatrixOptions
ModuleNotFoundError: No module named 'rgbmatrix.core'

```
This is the error message I got when I tried to run the nextbus transit timer project from adafruit:

```
Traceback (most recent call last):
File "nextbus-matrix.py", line 5, in <module>
import Image
ImportError: No module named Image
```

(I have a-lot more code from the first one as it was yesterday.)

I have spoken to the following, and no one seems to know why I get this error message:

Adafruit support- mike (forums)

u/bder222 (developer of MLB scoreboard on GitHub) - I dm'ed him, and we tried a little bit of troubleshooting code.  That error was after trying to run a preloaded python board test.  He said that he's tried it on new boards, and it always works fine, so im kinda lost. 

Hardware info:

- Raspberry pi zero WH
- Adafruit 16x32 dot matrix display 6mm pitch (2, currently only using one)
- Adafruit dot matrix bonnet
- 5v 4a switching power supply

(From what I can tell the nextbus installs an older version of this library, however I have tried installing the new one, and I know that the NBA scoreboard installs a new version)

(Some code / comments copied from my post on reddit)

If anyone here could help, or has any experience with this kind of error, that would be much appreciated

Thanks

**Comment by xuniuer** [comment]
Maybe you should install pillow package for Image

````pip install pillow``

**Comment by Gamereric21** [comment]
I can definitely try that.  I tried it on the Nextbus before, but ill see what I can do with the NBA scoreboard!

**Comment by Gamereric21** [comment]
> Maybe you should install pillow package for Image
> 
> ````pip install pillow``

I tried that!  still getting that error for some reason.  Know anything else that may help?

**Comment by xuniuer** [comment]
Some points to check:
1. Python3/pip3 is available by default? If not, please use ```pip3 install pillow``` 
2. Could use original project to make python binding, then ```make install``` under bindings/python directory to install python extension to your system
3. Start a python shell, try to ```import rgbmatrix``` to validate

**Comment by marcmerlin** [comment]
With apologies to everyone, this project is doing a one time cleanup of 
all the bugs that have not been addressed and closed in the last 10 years.

If you filed an issue to ask for help, please do not re-open this one or a new
bug, but go here instead: https://rpi-rgb-led-matrix.discourse.group/

Please be mindful that this project does not have any full time maintainers
or anyone paid. You should not expect personal help for your own projects or
answers to programming questions but you can ask for help with panels that
aren't working, setup questions, or anything that may be a bug here:
https://rpi-rgb-led-matrix.discourse.group/
If you need programming help and are willing to pay someone for it, please
state so in your message, and someone may be interested.

If you did report an actual bug that is still not fixed today, please accept
our apologies for this being mass closed, you can absolutely send a followup
and re-open the issue, or open a new up to date one as applicable.
Note that we very much welcome help, so if you can help fix your bug, you will
be a superstar :)

If your bug was linked to a pull request that was not resolved, please update
the pull request and the issue, and we will do our best to review them. We do
thank you for your undertanding that we have very limited free time, so any
extra work you do along with your bug report or PR request will be very much
appreciated and improve the odds that they will be looked at.

If you want to help contribute as a python or C# or any other language bindings,
you are also a superstar, please state so in the issue and we'll do our best to
give you the access and reviews you need.

For anything related to PWM panel support, please make sure you read README and
then refer to https://github.com/hzeller/rpi-rgb-led-matrix/issues/466 . 
Please do not comment if you're haven't read everything and/or if you're just
asking when your panel is going to be supported. Those bugs are if you're 
able to contribute to the effort.

For rPI5: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1603

For anything python, please link your bug to: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1828
For anything C#, please link your bug to: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1828
