### ISSUE TITLE
Python thread + SetImage = OverflowError: can't convert negative value to size_t

### ISSUE THREAD

**Issue by sufinawaz** [hzeller/rpi-rgb-led-matrix#1505]
Hi I'm trying to make sense of an issue I'm seeing when I'm trying to use the python examples with python threads. In my actual app, I receive messages from an mqtt queue and depending on the payload, I show different pieces of information on my 32x64 led matrix display. The idea of using  threads is so that each operation runs independently without blocking parent flow. 

Of note, I'm able to use this completely fine if:

1. I don't use threads.
2. I don't call SetImage even if I use threads.

Here's a quick version of the code. 

```
#!/usr/bin/env python
import time
from samplebase import SampleBase
from rgbmatrix import graphics
from PIL import Image
import threading

fontSmall = graphics.Font()
fontSmall.LoadFont("/home/pi/code/matrix/fonts/4x6.bdf")


class InfoCube(SampleBase):

    def __init__(self, *args, **kwargs):
        super(InfoCube, self).__init__(*args, **kwargs)

    def run(self):
        # this works
        # display_weather(self, None)
        
        # but this does not
        thread1 = threading.Thread(target=display_weather, args=(self, None))
        thread1.start()


def display_weather(infocube, _):
    infocube.image = Image.open('weather-icons/11d.jpg').convert('RGB')
    infocube.image.resize((infocube.matrix.width, infocube.matrix.height), Image.ANTIALIAS)
    double_buffer = infocube.matrix.CreateFrameCanvas()
    while True:
        double_buffer.SetImage(infocube.image, 1, -10)
        graphics.DrawText(double_buffer, fontSmall, 5, 8, graphics.Color(255, 0, 0), "text on image")
        double_buffer = infocube.matrix.SwapOnVSync(double_buffer)

        # break condition goes here if queue is not empty


if __name__ == "__main__":
    image_scroller = InfoCube()
    if (not image_scroller.process()):
        image_scroller.print_help()

```
This is how I run the script: `# python infocube.py -b 20 --led-cols=64 --led-rows=32 --led-no-drop-privs --led-rgb-sequence=RBG`

This is the error i get (fwiw, I'm using Python 3.9.2):
```Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/code/matrix/bindings/python/samples/test-image2.py", line 30, in display_weather
    double_buffer.SetImage(infocube.image, 1, -10)
  File "core.pyx", line 22, in rgbmatrix.core.Canvas.SetImage
  File "core.pyx", line 46, in rgbmatrix.core.Canvas.SetPixelsPillow
OverflowError: can't convert negative value to size_t
```

I've isolated the problem to be thread related with the use of images but I'm not sure how to get around this error. Any help would be greatly appreciated.

**Comment by sufinawaz** [comment]
Ok changing to this: `double_buffer.SetImage(infocube.image, 1, -10, False)` to enable unsafe mode did the trick 🎉
