### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by MiguelElBigodon** [hzeller/rpi-rgb-led-matrix#1654]
I have the following error:
FYI: not running as root which means we can't properly control timing unless this is a real-time kernel. Expect color degradation. Consider running as root with sudo.

How can I solve this problem?

I have the adafruit matrix hat+real time clock board, two 16x32 matrices and a Raspberry Pi 4b.

**Comment by hzeller** [comment]
On Thu, May 16, 2024, 11:48 MiguelElBigodon ***@***.***>
wrote:

> I have the following error:
> FYI: not running as root which means we can't properly control timing
> unless this is a real-time kernel. Expect color degradation. Consider
> running as root with sudo.
>
> How can I solve this problem?
>

Run with sudo

I have the adafruit matrix hat+real time clock board, two 16x32 matrices

**Comment by MiguelElBigodon** [comment]
The problem:

sudo python3 /home/migasboss/rpi-rgb-led-matrix/bindings/python/samples/runtext.py Press CTRL-C to stop sample Traceback (most recent call last): File "/home/migasboss/rpi-rgb-led-matrix/bindings/python/samples/runtext.py", line 33, in <module> File "/home/migasboss/rpi-rgb-led-matrix/bindings/python/samples/samplebase.py", line 76, in process File "/home/migasboss/rpi-rgb-led-matrix/bindings/python/samples/runtext.py", line 14, in run File "graphics.pyx", line 32, in rgbmatrix.graphics.Font.LoadFont Exception: Couldn't load font ../../../fonts/4x6.bdf

Fonts imagem
![IMG_20240516_202842.jpg](https://github.com/hzeller/rpi-rgb-led-matrix/assets/166311001/5d7768dc-8818-4110-9a85-f3da786b001d)

Runtext:
from samplebase import SampleBase 
from rgbmatrix import graphics
 import time class
 RunText(SampleBase): def __init__(self, *args, **kwargs): super(RunText, self).__init__(*args, **kwargs) self.parser.add_argument("-t", "--text", help="The text to scroll on the RGB LED panel", default="MECATRONICA") def run(self): offscreen_canvas = self.matrix.CreateFrameCanvas() font = graphics.Font() font.LoadFont("../../../fonts/4x6.bdf") textColor = graphics.Color(255, 255, 0) pos = offscreen_canvas.width my_text = self.args.text while True: offscreen_canvas.Clear() len = graphics.DrawText(offscreen_canvas, font, pos, 25, textColor, my_text) pos -= 1 if (pos + len < 0): pos = offscreen_canvas.width time.sleep(0.05) offscreen_canvas = self.matrix.SwapOnVSync(offscreen_canvas) # Main function if __name__ == "__main__": run_text = RunText() if (not run_text.process()): run_text.print_help()

**Comment by MiguelElBigodon** [comment]
I'm having the problem mentioned above, which says I don't have the bdf files but they're all in the folder where they should be.

**Comment by davemaster** [comment]
A little more reading of "README.MD" in this repository, and problem solved... a little more. An advice, before using python scripts, try using the demo within the examples-api-use folder.

Best regards

PD. IN python, the code must be PERFECTLY indented, otherwise... ERROR everywhere...

**Comment by marcmerlin** [comment]
With apologies to everyone, this project is doing a one time cleanup of 
all the bugs that have not been addressed and closed in the last 10 years.

If you filed an issue to ask for help, please do not re-open this one or a new
bug, but go here instead: https://rpi-rgb-led-matrix.discourse.group/

Please be mindful that this project does not have any full time maintainers
or anyone paid. You should not expect personal help for your own projects or
answers to programming questions but you can ask for help with panels that
aren't working, setup questions, or anything that may be a bug here:
https://rpi-rgb-led-matrix.discourse.group/
If you need programming help and are willing to pay someone for it, please
state so in your message, and someone may be interested.

If you did report an actual bug that is still not fixed today, please accept
our apologies for this being mass closed, you can absolutely send a followup
and re-open the issue, or open a new up to date one as applicable.
Note that we very much welcome help, so if you can help fix your bug, you will
be a superstar :)

If your bug was linked to a pull request that was not resolved, please update
the pull request and the issue, and we will do our best to review them. We do
thank you for your undertanding that we have very limited free time, so any
extra work you do along with your bug report or PR request will be very much
appreciated and improve the odds that they will be looked at.

If you want to help contribute as a python or C# or any other language bindings,
you are also a superstar, please state so in the issue and we'll do our best to
give you the access and reviews you need.

For anything related to PWM panel support, please make sure you read README and
then refer to https://github.com/hzeller/rpi-rgb-led-matrix/issues/466 . 
Please do not comment if you're haven't read everything and/or if you're just
asking when your panel is going to be supported. Those bugs are if you're 
able to contribute to the effort.

For rPI5: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1603

For anything python, please link your bug to: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1828
For anything C#, please link your bug to: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1828
