### ISSUE TITLE
--led-rgb-sequence has no effect at all

### ISSUE THREAD

**Issue by devjb** [hzeller/rpi-rgb-led-matrix#446]
I have one 32x64 panel here that has G and B swapped. But no matter which --led-rgb-sequence I use, nothing changes at all. I am driving the panel with an old PI (1st gen), and thus I have --led-gpio-mapping=regular-pi1 set as well. But I do not think that it is related, because the colors are swapped nonetheless, even when not set.

Any idea, why this could happen?

**Comment by angelogoncalve** [comment]
You can do this:

from rgbmatrix import RGBMatrix, RGBMatrixOptions

def rgbmatrix_options():
      options = RGBMatrixOptions()
      options.led_rgb_sequence = "RBG"
      options.rows = 32
      options.chain_length = 2
      options.parallel = 1
      options.hardware_mapping = 'adafruit-hat'
      return options

options = self.rgbmatrix_options()
display = RGBMatrix(options=options)

**Comment by hzeller** [comment]
Ah, are you using Python @devjb ?

**Comment by devjb** [comment]
Thank you for your comment. But I do not user the python bindings and no adafruit hat. But if you suggest to set everything manually in RGBMatrix::Options instead of passing it by the parameters, I for sure could give this a try.

**Comment by hzeller** [comment]
Mmh, the `--led-rgb-sequence=RBG` should work though.

**Comment by hzeller** [comment]
did this work ?

**Comment by devjb** [comment]
Not yet so far. I've had little time lately and did not further investigate. I got a pi 3  lastweek and will test the panel there again. I will reopen here if necessary.

**Comment by javadbahmani1372** [comment]
i have an error 

my options :
var options = new RGBLedMatrixOptions()
{
    Brightness = 80,
    Cols = 80,
    Rows = 40,
    ChainLength = 2,
    Multiplexing = Multiplexing.Direct,
    PixelMapperConfig = "V-mapper",
    GpioSlowdown = 4,
    LedRgbSequence = "RBG"
};

error : 
led-sequence needs to be three characters long.

fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      System.ArgumentException: Could not initialize a new matrix
         at RPiRgbLEDMatrix.RGBLedMatrix..ctor(RGBLedMatrixOptions options) in D:\TFSWorkspace\Git\SmartBox\RPiRgbLEDMatrix\RGBLedMatrix.cs:line 60
         at SmartBox.Player.Worker.Show(String path, TimeSpan duration) in D:\TFSWorkspace\Git\SmartBox\SmartBox.Player\Worker.cs:line 91
         at SmartBox.Player.Worker.ExecuteAsync(CancellationToken stoppingToken) in D:\TFSWorkspace\Git\SmartBox\SmartBox.Player\Worker.cs:line 56
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      System.ArgumentException: Could not initialize a new matrix
         at RPiRgbLEDMatrix.RGBLedMatrix..ctor(RGBLedMatrixOptions options) in D:\TFSWorkspace\Git\SmartBox\RPiRgbLEDMatrix\RGBLedMatrix.cs:line 60
         at SmartBox.Player.Worker.Show(String path, TimeSpan duration) in D:\TFSWorkspace\Git\SmartBox\SmartBox.Player\Worker.cs:line 91
         at SmartBox.Player.Worker.ExecuteAsync(CancellationToken stoppingToken) in D:\TFSWorkspace\Git\SmartBox\SmartBox.Player\Worker.cs:line 56
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)

**Comment by marcmerlin** [comment]
@javadbahmani1372  if you have a C# issue, please discuss in #1828
