### ISSUE TITLE
Error when running image-scroller

### ISSUE THREAD

**Issue by popeyesfx** [hzeller/rpi-rgb-led-matrix#501]
Hi
I have had this code running on a pi zero and keep getting an error message.
The code is an older version (needed for compatability with other parts of my project)

There seems to be 2 issues

1. when i run
sudo  apt-get update && sudo apt-get install python3-dev python3-pillow -y
i get the following output 
Note, selecting 'python3-pil' instead of 'python3-pillow'
python3-dev is already the newest version.
python3-pil is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

then when i run my project i get 
Traceback (most recent call last):
  File "/home/pi/pywork/pibanner/image-scroller.py", line 3, in <module>
    from samplebase import SampleBase
  File "/home/pi/pywork/pibanner/samplebase.py", line 5, in <module>
    from rgbmatrix import RGBMatrix, RGBMatrixOptions
  File "/usr/local/lib/python3.4/dist-packages/rgbmatrix/__init__.py", line 7, in <module>
    from .core import RGBMatrix, FrameCanvas, RGBMatrixOptions
  File "rgbmatrix/core.pyx", line 5, in init rgbmatrix.core (rgbmatrix/core.cpp:6667)
ImportError: No module named 'PIL'

i have built the python code and installed it and rebooted the pi.

it has worked before, so im not sure what i have missed

thanks for your help

**Comment by popeyesfx** [comment]
Its ok if found the issue
I had installed pillow 5 before installing the matrix code and it had broken something.
reinstalling the matrix code then reinstalling the pillow 5 code fixed it
