### ISSUE TITLE
Exception: No module named core

### ISSUE THREAD

**Issue by TenchiMuyo1984** [hzeller/rpi-rgb-led-matrix#905]
Hello, I've a problem executing the samples fpr python.

I get everytime this exception:
`PS D:\Downloads\Chrome\rpi-rgb-led-matrix-master\bindings\python\samples> python runtext.py
Traceback (most recent call last):
  File "runtext.py", line 3, in <module>
    from samplebase import SampleBase
  File "D:\Downloads\Chrome\rpi-rgb-led-matrix-master\bindings\python\samples\samplebase.py", line 7, in <module>
    from rgbmatrix import RGBMatrix, RGBMatrixOptions
  File "D:\Downloads\Chrome\rpi-rgb-led-matrix-master\bindings\python\rgbmatrix\__init__.py", line 7, in <module>
    from .core import RGBMatrix, FrameCanvas, RGBMatrixOptions
ImportError: No module named core
PS D:\Downloads\Chrome\rpi-rgb-led-matrix-master\bindings\python\samples>`

I was thinking, that the core.pyx has a wrong ending and I changed from .pyx to .py
Try again and I got this exception:

`PS D:\Downloads\Chrome\rpi-rgb-led-matrix-master\bindings\python\samples> python runtext.py
Traceback (most recent call last):
  File "runtext.py", line 3, in <module>
    from samplebase import SampleBase
  File "D:\Downloads\Chrome\rpi-rgb-led-matrix-master\bindings\python\samples\samplebase.py", line 7, in <module>
    from rgbmatrix import RGBMatrix, RGBMatrixOptions
  File "D:\Downloads\Chrome\rpi-rgb-led-matrix-master\bindings\python\rgbmatrix\__init__.py", line 7, in <module>
    from .core import RGBMatrix, FrameCanvas, RGBMatrixOptions
  File "D:\Downloads\Chrome\rpi-rgb-led-matrix-master\bindings\python\rgbmatrix\core.py", line 4
    from libc.stdint cimport uint8_t, uint32_t, uintptr_t
                           ^
SyntaxError: invalid syntax
PS D:\Downloads\Chrome\rpi-rgb-led-matrix-master\bindings\python\samples>`

What I do wrong?

My target is to run a 32x64 with FM6124 on it with a RasPy3b+ and python (2.7).

**Comment by hzeller** [comment]
the paths mentioned in that error message indicate that you're running this on some windows-based system? You want to compile that on your Pi.

**Comment by TenchiMuyo1984** [comment]
For this example, yes. It was a traceback from my Win10.
But I got the same on my RasPy.

I'm able to execute the demo by using: 
`sudo examples-api-use/demo -D0`

`pi@raspberrypi:~/rpi-rgb-led-matrix-master $ sudo examples-api-use/demo -D0
Size: 32x32. Hardware gpio mapping: regular
Press <CTRL-C> to exit and reset LEDs`

Sadly I've two squares rotating on my display....
But how can I execute a python code only?
I wanted to try this:
`pi@raspberrypi:~/rpi-rgb-led-matrix-master/bindings/python/samples $ python runtext.py'
but got this:

'Traceback (most recent call last):
  File "runtext.py", line 3, in <module>
    from samplebase import SampleBase
  File "/home/pi/rpi-rgb-led-matrix-master/bindings/python/samples/samplebase.py", line 7, in <module>
    from rgbmatrix import RGBMatrix, RGBMatrixOptions
  File "/home/pi/rpi-rgb-led-matrix-master/bindings/python/rgbmatrix/__init__.py", line 7, in <module>
    from .core import RGBMatrix, FrameCanvas, RGBMatrixOptions
ImportError: No module named core
pi@raspberrypi:~/rpi-rgb-led-matrix-master/bindings/python/samples $`

Or here are no examples in python?

**Comment by hzeller** [comment]
If you have two squares: do you happen to have a 64x32 panel ? Then you need to give it `--led-cols=64` parameter.

As for Python: Please follow the instructions to install it as described in the readme https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/bindings/python

**Comment by TenchiMuyo1984** [comment]
Thank you for your time!

> If you have two squares: do you happen to have a 64x32 panel ? 
Yes, look in the last line of my first post ;)

>Then you need to give it `--led-cols=64` parameter.
Thank you, that was it!
 
> As for Python: Please follow the instructions to install it as described in the readme https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/bindings/python

I've done this, but:
`sudo apt-get update && sudo apt-get install python2.7-dev python-pillow -y`
Was working fine.
`make build-python`
Didn't worked at the first try. I needed to change the directory. 
`sudo make install-python`
Same problem as before. I don't know why I must change the directory ...

But now, It works to execute the .py examples *thumbs up*

And maybe I'm stupid, but why I must use "sudo ./" at beginning? I use normaly "python demo.py" and that was it.

As Information. When I execute this code, I got a messy picture:
`sudo ./image-scroller.py --led-chain=2 --led-slowdown-gpio 0`


A new question:
Is it possible to change (decrease) the frequency to see a really slow buildup of the objects (pictures, symbols, etc.)?

**Comment by arahasya** [comment]
hello. How did you run FM6124. I have the  same panel but not getting correct output

**Comment by PoojaPremnath2003** [comment]
@TenchiMuyo1984 - If I may ask, which directly did you change to- before executing the make build-python statement? I'm facing the same issue now, and am trying to fix it.

**Comment by marcmerlin** [comment]
With apologies to everyone, this project is doing a one time cleanup of 
all the bugs that have not been addressed and closed in the last 10 years.

If you filed an issue to ask for help, please do not re-open this one or a new
bug, but go here instead: https://rpi-rgb-led-matrix.discourse.group/

Please be mindful that this project does not have any full time maintainers
or anyone paid. You should not expect personal help for your own projects or
answers to programming questions but you can ask for help with panels that
aren't working, setup questions, or anything that may be a bug here:
https://rpi-rgb-led-matrix.discourse.group/
If you need programming help and are willing to pay someone for it, please
state so in your message, and someone may be interested.

If you did report an actual bug that is still not fixed today, please accept
our apologies for this being mass closed, you can absolutely send a followup
and re-open the issue, or open a new up to date one as applicable.
Note that we very much welcome help, so if you can help fix your bug, you will
be a superstar :)

If your bug was linked to a pull request that was not resolved, please update
the pull request and the issue, and we will do our best to review them. We do
thank you for your undertanding that we have very limited free time, so any
extra work you do along with your bug report or PR request will be very much
appreciated and improve the odds that they will be looked at.

If you want to help contribute as a python or C# or any other language bindings,
you are also a superstar, please state so in the issue and we'll do our best to
give you the access and reviews you need.

For anything related to PWM panel support, please make sure you read README and
then refer to https://github.com/hzeller/rpi-rgb-led-matrix/issues/466 . 
Please do not comment if you're haven't read everything and/or if you're just
asking when your panel is going to be supported. Those bugs are if you're 
able to contribute to the effort.

For rPI5: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1603

For anything python, please link your bug to: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1828
For anything C#, please link your bug to: https://github.com/hzeller/rpi-rgb-led-matrix/issues/1828
